dist: trusty
sudo: false

language: php
php:
  - 5.6
  - 7

services:
  - mysql

env:
  global:
    - BRANCH=master
    - REPO=nc
  matrix:
    - DB=mysql

matrix:
  include:
    - php: 5.6
      env: DB=sqlite
    - php: 5.6
      env: DB=pgsql
    - php: 5.6
      env: DB=mysql BRANCH=stable10
    - php: 5.6
      env: DB=mysql BRANCH=stable11
    - php: 5.6
      env: DB=mysql BRANCH=stable12



install:
 - which mysql && until mysql -u root -e "show status" &>/dev/null; do sleep 1; done
 - ./tests/travis/install-$REPO-$BRANCH.sh

# Note the install script should make sure we are in the apps/ojsxc directory
script:
  - composer install
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover=unit-coverage.xml
  - ./vendor/bin/phpunit -c phpunit.integration.xml --coverage-clover=integration-coverage.xml
  - cat ../../data/nextcloud.log
  - vendor/bin/php-cs-fixer fix --dry-run --using-cache=no
  - rm -r build/ && rm -r vendor/ && ../../occ app:check-code ojsxc

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm install -g bower
  - make nightly
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/github-deploy-key
  - ssh-add .travis/github-deploy-key
  - git clone git@github.com:jsxc/nightly-builds.git
  - mv archives/ojsxc-nightly-latest.tar.gz nightly-builds/
  - cd nightly-builds/
  - git add .
  - git commit -m "build nextcloud/jsxc.nextcloud@$TRAVIS_COMMIT"
  - git push

before_install:
  - openssl aes-256-cbc -K $encrypted_2fb4f9166ccf_key -iv $encrypted_2fb4f9166ccf_iv -in .travis/github-deploy-key.enc -out .travis/github-deploy-key -d
